In [7]:
import numpy as np
from randn2 import randn2

### Use the same Seed from Matlab

In [8]:
seed_from_matlab = 43

np.random.seed(seed_from_matlab)

In [9]:
print(randn2(5,4))

[[-1.2001  0.2769 -1.1105 -0.7044]
 [-0.4478  1.0765  0.4291  0.1034]
 [-1.8955  0.6242 -0.2664  0.849 ]
 [-0.6606 -1.5815  1.1107 -0.7687]
 [-0.2405 -0.4786 -1.4279  1.0078]]


In [10]:
print(randn2(5,4))

[[ 1.0319  1.9028 -0.2914  1.69  ]
 [-0.1364  0.4392 -1.3884  1.2652]
 [-0.5302 -0.6363 -2.567   0.1085]
 [-0.0612  0.3488  2.018   1.3326]
 [ 1.3417  0.0633 -1.259  -0.9119]]
